import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Header from "@/components/Header/Header";
// import HeaderProduct from "@/components/HeaderProduct/HeaderProduct";
import { Poppins } from "next/font/google";
import HeaderAbout from "@/components/HeaderAbout/HeaderAbout";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Poppins({
  subsets: ['latin'], // Choose subsets based on your needs
  weight: ['400', '700'], // Specify the weights you need
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.className}`}
      >
        {/* <Header/> */}
        <HeaderAbout/>
        {/* <HeaderProduct/> */}
        {children}
      </body>
    </html>
  );
}
